# Change these first
owner: Subaru-SciOp # Your GitHub organization or username, where this repository lives
repo: subaru-sciop-status # The name of this repository

# add delay between scans
delay: 5000

sites:
  - name: PSF Spectral Simulator
    url: https://pfs-etc.naoj.hawaii.edu/etc/doc/index.html
    method: GET
    __dangerous__insecure: true
  - name: PFS Target Uploader Docs
    url: https://pfs-etc.naoj.hawaii.edu/uploader/doc/index.html
    method: GET
    __dangerous__insecure: true
  - name: PFS Flux Standard Star Lookup
    url: https://pfs-etc.naoj.hawaii.edu/fluxstd-lookup/app
    method: GET
    __dangerous__insecure: true
  - name: PSF Target Database Docs
    url: https://subaru-pfs.github.io/ets_target_database/
    method: GET
  - name: PFS Jira
    url: https://pfs-jira.naoj.org/jira/
    method: GET
  # # Test purpose
  # - name: Notification Test
  #   # url: https://mock.httpstatus.io/503
  #   url: https://mock.httpstatus.io/200
  #   method: GET

status-website:
  # # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: ocean
  baseUrl: /subaru-sciop-status
  logoUrl: https://raw.githubusercontent.com/Subaru-SciOp/subaru-sciop-status/master/assets/subaru_logo2_rgb_aligned_s.png
  name: Subaru Telescope Science Operation Web Service Status
  introTitle: Subaru Telescope Science Operation Status shows service status for the science operation of Subaru Telescope.
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # disallow search engine crawling
  robotsText: "User-agent: * \n Disallow: /"

workflowSchedule:
  # run uptime workflow every 30 minutes
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
